Upgrade Cake
DNNCommunity/Dnn.CakeUtils pull request #1
Opened 2021-03-17 15:05 UTC by bdukes

The build failure for https://github.com/dnnsoftware/Dnn.Platform/pull/4554 is coming from a method signature change between Cake 0.37.0 (which this project currently references) and Cake 1.x (which DNN references).

This PR upgrades the version of Cake referenced by this project to 1.0.0 to avoid these conflicts.

It also adjusts the API to use Cake's path types and to use Cake for logging where appropriate.

Because of the breaking changes in the API surface, this also bumps the version to 2.0.0

2021-03-17 15:05 UTC, bdukes commented
@donker let me know if there's anything in here you'd like me to adjust.  Thanks!

2021-03-17 17:53 UTC, valadas approved these changes
Looks good to me

2021-03-18 17:35 UTC, donker requested changes
My builds are unfortunately broken with this change. I've discovered some awkward behavior in how Cake deals with paths. If I have a relative path, then new DirectoryPath(path) and then getting FullPath gives back the original relative path, not the expected full path to the target,

2021-03-18 17:35 UTC, donker commented on Compression.cs
> +        public static void AddFilesToZip(this ICakeContext context, FilePath zipFile, DirectoryPath root, FilePathCollection files)
I think the changes to start and newStart need to be reverted. I understand the move to FilePath for the zipfile, but the other are strings that indicate how the path should be rewritten for the zip file. This change, in any case, makes a complete mess of my distribution zips.

2021-03-18 17:35 UTC, donker commented on Compression.cs
> +        public static void AddStreamToZip(this ICakeContext context, FilePath zipFile, Stream fileToZip, FilePath name, bool append)
Same here. The name serves as a name to put in the zip. It's not an existing FilePath.

2021-03-18 21:49 UTC, bdukes commented
@donker I've adjusted the places where I'm expecting a full path to use `MakeAbsolute`, and reverted the `name` and `newStart` fields to use `string` instead of `FilePath`/`DirectoryPath`. Let me know if that resolves your issues or if there's anything more that you find needs adjusting.

2021-03-19 09:02 UTC, donker approved these changes
OK, that fixed those issues. We'll go with this.

2021-03-19 09:02 UTC, merged